/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PeripheralMigrationContract__factory } from "./PeripheralMigrationContract__factory";
export { PeripheralPRL__factory } from "./PeripheralPRL__factory";
