/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PeripheralMigrationContract } from "./PeripheralMigrationContract";
export type { PeripheralPRL } from "./PeripheralPRL";
